# -*- coding: utf-8 -*-
"""Capston 4 Beby.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OcDYVQJ1KLXn3Ya8JHX6XoAm3TcEBs-l
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -qU ultralytics supervision

!pip install ultralytics --upgrade

import ultralytics
ultralytics.checks()

!pip install ultralytics roboflow supervision

from roboflow import Roboflow

rf = Roboflow(api_key="wraQ5Z8NaxoKsxyt9TFm")
project = rf.workspace("ayu-asipq").project("calory")
dataset = project.version(1).download("yolov11")

"""TRAINING YOLOv11"""

!ls /content

import torch
device = 0 if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

# ==============================
# Setup environment dan load model YOLO
# ==============================
import torch
from ultralytics import YOLO

# ==============================
# Tentukan device otomatis: GPU jika ada, CPU jika tidak
# ==============================
device = 0 if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

# ==============================
# Safe globals untuk mencegah UnpicklingError
# ==============================
torch.serialization.add_safe_globals([torch.nn.modules.container.Sequential])

# ==============================
# Load model YOLO
# ==============================
model_path = '/content/drive/MyDrive/Capstone 4/yolo11n.pt'  # sesuaikan path
model = YOLO(model_path)
print("✅ Model YOLO berhasil dimuat!")

# ==============================
# Training model (dioptimalkan untuk CPU / Colab gratis)
# ==============================
# Tips optimasi:
# - Kurangi ukuran gambar: 416 → lebih ringan
# - Kurangi batch size: 4-8 → lebih aman di CPU
# - Kurangi epoch jika hanya testing
model.train(
    data="/content/Calory-1/data.yaml",   # sesuaikan path YAML
    epochs=20,      # turunkan epoch untuk mempercepat
    imgsz=416,      # turunkan ukuran gambar
    batch=4,        # batch kecil supaya tidak berat di CPU
    patience=10,
    pretrained=True,
    device=device   # otomatis GPU/CPU
)

print("✅ Training selesai!")

!find /content/runs/detect -name "best.pt"

!cp /content/runs/train/exp/best.pt /content/drive/MyDrive/

!pip install -qU ultralytics supervision

import cv2
import supervision as sv
from ultralytics import YOLO

import glob

weights_files = glob.glob("/content/runs/train/**/*.pt", recursive=True)
print(weights_files)

from ultralytics import YOLO

model = YOLO("/content/runs/detect/train3/weights/best.pt")

calorie_info = {
    "Ayam Goreng": "260 kal / 100 g",
    "Capcay": "67 kal / 100 g",
    "Nasi": "129 kal / 100 g",
    "Sayur Bayam": "36 kal / 100 g",
    "Sayur Kangkung": "98 kal / 100 g",
    "Sayur Sop": "22 kal / 100 g",
    "Tahu": "80 kal / 100 g",
    "Telur Dadar": "93 kal / 100 g",
    "Telur Mata Sapi": "110 kal / 1 butir",
    "Telur Rebus": "78 kal / 1 butir",
    "Tempe": "225 kal / 100 g",
    "Tumis Buncis": "65 kal / 100 g",
    "food-z7P4": "-"
}

image = cv2.imread('/content/drive/MyDrive/Capstone 4/test_food.jpg')

# Inference
results = model(image, verbose=False)[0]
detections = sv.Detections.from_ultralytics(results).with_nms()

# Annotators
box_annotator = sv.BoxAnnotator(thickness=2)
label_annotator = sv.LabelAnnotator(
    text_scale=0.8,
    text_thickness=2,
    text_padding=5
)

# ------------ FORMAT LABEL PER BARIS -------------
labels = []
for class_id in detections.class_id:
    raw_name = model.names[int(class_id)]  # contoh: "Nasi -129 kal per 100gr-"

    # Pisahkan 2 bagian (nama & kalori)
    parts = raw_name.split("-")
    food_name = parts[0].strip()                   # "Nasi"
    calorie_raw = parts[1].replace("kal per", "").replace("100gr", "").strip()

    # Format lebih rapi → "129 kal/100gr"
    calorie_clean = f"{calorie_raw} kal/100gr"

    # Gabungkan jadi 2 baris
    label = f"{food_name}\n{calorie_clean}"
    labels.append(label)
# --------------------------------------------------

# Draw annotation
annotated_image = box_annotator.annotate(
    scene=image.copy(),
    detections=detections
)

annotated_image = label_annotator.annotate(
    scene=annotated_image,
    detections=detections,
    labels=labels
)

sv.plot_image(annotated_image)

detections

detections